// <auto-generated />
namespace FinalWhistle.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class matchreport3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(matchreport3));
        
        string IMigrationMetadata.Id
        {
            get { return "201610171951518_match report 3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
